# Generated by Django 4.2.7 on 2023-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
