# Generated by Django 4.2.7 on 2023-11-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email_contact_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
