# Generated by Django 4.2.7 on 2023-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_client_last_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_id',
            field=models.EmailField(blank=True, editable=False, max_length=254, null=True),
        ),
    ]
