# Generated by Django 4.2.7 on 2023-11-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_client_email_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
