# Generated by Django 4.2.7 on 2023-11-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0006_alter_client_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
