# Generated by Django 4.2.7 on 2023-12-15 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_alter_event_client_alter_event_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Support team'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_contact_events', to=settings.AUTH_USER_MODEL, verbose_name='Support Contact'),
        ),
    ]
