# Generated by Django 4.2.7 on 2023-12-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_client_user_contact'),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_contracts', to='profiles.client', verbose_name='Client'),
        ),
    ]
